### ISSUE TITLE
Image processing with stardist

### ISSUE THREAD

**Issue by alipirani88** [Sanofi-Public/enact-pipeline#11]
Hi, I am ex=ncountering this error while stardist image processing. Any idea what might be causing this error?

Traceback (most recent call last):
  File "/rsrch5/home/neuro_rsrch/apirani/2024_11_07_Enact_Demo/enact_915422.py", line 9, in <module>
    so_hd.run_enact()
  File "/home/apirani/.local/lib/python3.10/site-packages/enact/pipeline.py", line 999, in run_enact
    cell_labels, cell_polys = self.segment_cells(image=wsi_norm)
  File "/home/apirani/.local/lib/python3.10/site-packages/enact/pipeline.py", line 318, in segment_cells
    labels, polys = self.stardist_model.predict_instances_big(
  File "/home/apirani/.local/lib/python3.10/site-packages/stardist/models/base.py", line 930, in predict_instances_big
    blocks = BlockND.cover(img.shape, axes, block_size, min_overlap, context, grid)
  File "/home/apirani/.local/lib/python3.10/site-packages/stardist/big.py", line 448, in cover
    cover_1d = [Block.cover(*args) for args in zip(shape, block_size, min_overlap, context, grid)]
  File "/home/apirani/.local/lib/python3.10/site-packages/stardist/big.py", line 448, in <listcomp>
    cover_1d = [Block.cover(*args) for args in zip(shape, block_size, min_overlap, context, grid)]
  File "/home/apirani/.local/lib/python3.10/site-packages/stardist/big.py", line 186, in cover
    assert 0 <= min_overlap+2*context < block_size <= size
AssertionError

**Comment by Mena-SA-Kamel** [comment]
Can you provide me more context on the configurations you used and the size of the image to be able to reproduce your error? It seems like an issue on the Stardist side with the patching/restitching steps. Here is the part of the code that runs Stardist on the image: https://github.com/Sanofi-Public/enact-pipeline/blob/c1282932af1f73e825a5afdf4ca5a27ddc64a197/src/enact/pipeline.py#L317C13-L327C14
```            
labels, polys = self.stardist_model.predict_instances_big(
                image,
                axes="YXC",
                block_size=4096,
                prob_thresh=prob_thresh,
                nms_thresh=0.001,
                min_overlap=128,
                context=128,
                normalizer=None,
                n_tiles=(4, 4, 1),
            )
```
I suggest you change the `block_size` parameter. In a future release, we will allow users to specify the Stardist parameters as part of ENACT's parameters but for now it is hardcoded.

**Comment by alipirani88** [comment]
Hi,

These are the parameters I am using.

`analysis_name: "238688-HD01_915422-5-2"
run_synthetic: False # True if you want to run bin to cell assignment on synthetic dataset, False otherwise.
cache_dir: "/rsrch5/home/neuro_rsrch/apirani/2024_11_07_Enact_Demo/enact-pipeline/ENACT_supporting_files/output_files"
paths:
  wsi_path: "/rsrch5/home/neuro_rsrch/apirani/10X_Visium_HD_data/2024-07-23_H5_First_Batch/images/915422-5.2_bigtiff.tif"
  visiumhd_h5_path: "/rsrch5/home/neuro_rsrch/apirani/10X_Visium_HD_data/2024-07-23_H5_First_Batch/238688-HD01_915422-5-2/binned_outputs/square_002um/filtered_feature_bc_matrix.h5"
  tissue_positions_path: "/rsrch5/home/neuro_rsrch/apirani/10X_Visium_HD_data/2024-07-23_H5_First_Batch/238688-HD01_915422-5-2/binned_outputs/square_002um/spatial/tissue_positions.parquet"
steps:
  segmentation: True # True if you want to run segmentation
  bin_to_geodataframes: True # True to convert bin to geodataframes
  bin_to_cell_assignment: True # True to assign cells to bins
  cell_type_annotation: True # True to run cell type annotation
params:
  seg_method: "stardist" # Stardist is the only option for now
  patch_size: 4000 # Defines the patch size. The whole resolution image will be broken into patches of this size
  bin_representation: "polygon"  # or point TODO: Remove support for anything else
  bin_to_cell_method: "weighted_by_cluster" # or naive
  cell_annotation_method: "celltypist"
  cell_typist_model: "Human_Colorectal_Cancer.pkl"
  use_hvg: True # Only run analysis on highly variable genes + cell markers specified
  n_hvg: 1000 # Number of highly variable genes to use
  n_clusters: 4 
  chunks_to_run: [
    # "patch_2_0.csv",
    # "patch_2_1.csv",
  ]
cell_markers:
  # # Human Colon
  Epithelial: ["CDH1","EPCAM","CLDN1","CD2"]
  Enterocytes: ["CD55", "ELF3", "PLIN2", "GSTM3", "KLF5", "CBR1", "APOA1", "CA1", "PDHA1", "EHF"]
  Goblet cells: ["MANF", "KRT7", "AQP3", "AGR2", "BACE2", "TFF3", "PHGR1", "MUC4", "MUC13", "GUCA2A"]
  Enteroendocrine cells: ["NUCB2", "FABP5", "CPE", "ALCAM", "GCG", "SST", "CHGB", "IAPP", "CHGA", "ENPP2"]
  Crypt cells: ["HOPX", "SLC12A2", "MSI1", "SMOC2", "OLFM4", "ASCL2", "PROM1", "BMI1", "EPHB2", "LRIG1"]
  Endothelial: ["PECAM1","CD34","KDR","CDH5","PROM1","PDPN","TEK","FLT1","VCAM1","PTPRC","VWF","ENG","MCAM","ICAM1","FLT4"]     
  Fibroblast: ["COL1A1","COL3A1","COL5A2","PDGFRA","ACTA2","TCF21","FN"]
  Smooth muscle cell: ["BGN","MYL9","MYLK","FHL2","ITGA1","ACTA2","EHD2","OGN","SNCG","FABP4"]
  B cells: ["CD74", "HMGA1", "CD52", "PTPRC", "HLA-DRA", "CD24", "CXCR4", "SPCS3", "LTB", "IGKC"]
  T cells: ["JUNB", "S100A4", "CD52", "PFN1P1", "CD81", "EEF1B2P3", "CXCR4", "CREM", "IL32", "TGIF1"]
  NK cells: ["S100A4", "IL32", "CXCR4", "FHL2", "IL2RG", "CD69", "CD7", "NKG7", "CD2", "HOPX"]

  # # Mouse intestine
  # Enterocytes: ["Cbr1", "Plin2", "Gls", "Plin3", "Dab1", "Pmepa1", "Acsl5", "Hmox1", "Abcg2", "Cd36"]
  # Goblet cells: ["Manf", "Krt7", "Ccl9", "Muc13", "Phgr1", "Cdx2", "Aqp3", "Creb3L1", "Guca2A", "Klk1"]
  # Enteroendocrine cells: ["Fabp5", "Cpe", "Enpp2", "Chgb", "Alcam", "Chga", "Pax6", "Neurod1", "Cck", "Isl1"]
  # Paneth cells: ["Gpx2", "Fabp4", "Lyz1", "Kcnn4", "Lgals2", "Guca2B", "Lgr4", "Defa24", "Il4Ra", "Guca2A"]
  # Crypt cells: ["Prom1", "Hopx", "Msi1", "Olfm4", "Kcne3", "Bmi1", "Axin2", "Kcnq1", "Ascl2", "Lrig1"]
  # Smooth muscle cells: ["Bgn", "Myl9", "Pcp4L1", "Itga1", "Nrp2", "Mylk", "Ehd2", "Fabp4", "Acta2", "Ogn"]
  # B cells: ["Cd52", "Bcl11A", "Ebf1", "Cd74", "Ptprc", "Pold4", "Ighm", "Cd14", "Creld2", "Fli1"]
  # T cells: ["Cd81", "Junb", "Cd52", "Ptprcap", "H2-Q7", "Ccl6", "Bcl2", "Maff", "Ccl4", "Ccl3"]
  # NK cells: ["Ctla2A", "Ccl4", "Cd3G", "Ccl3", "Nkg7", "Lat", "Dusp2", "Itgam", "Fhl2", "Ccl5"]`
  
  The size of the image is 4.5G in bigtiff format.
  
  I am experiencing another issue - Since I am running the job on HPC, I dont have the ability to access internet and the job fails with connection timeout error. Can we manually download the models and give access to them from configuration settings?

`Exception: 🛑 Cannot fetch 'https://celltypist.cog.sanger.ac.uk/models/models.json', the error is: HTTPSConnectionPool(host='celltypist.cog.sanger.ac.uk', port=443): Max retries exceeded with url: /models/models.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x15530db93bb0>, 'Connection to celltypist.cog.sanger.ac.uk timed out. (connect timeout=30)'))`

Thanks,

**Comment by Mena-SA-Kamel** [comment]
We are planning on adding support to custom Stardist model weights, but in the mean time, please try modifying this [line](https://github.com/Sanofi-Public/enact-pipeline/blob/c1282932af1f73e825a5afdf4ca5a27ddc64a197/src/enact/pipeline.py#L316) with the path to your model:

`self.stardist_model = StarDist2D.from_pretrained("<path-to-custom-model>")`

**Comment by AtlasMaroc** [comment]
@Mena-SA-Kamel I am getting a similar error, is the problem solved ?. @alipirani88 were you able to solve the problem?

2026-01-16 14:24:53,206 - ENACT - INFO - <initiate_instance_variables> ENACT running with the following configurations: 
 analysis_name: sample_P
 run_synthetic: False
 cache_dir: ./
 wsi_path: /pasteur/helix/projects/CSD_hpc/data/lab/spatial/embryo_head_VisiumHD/images/A1_highres_RGB.tif
 visiumhd_h5_path: /pasteur/helix/projects/CSD_hpc/data/lab/spatial/embryo_head_VisiumHD/TenXcountsOutputs/Shah_24_3165p/outs/binned_outputs/square_002um/filtered_feature_bc_matrix.h5
 tissue_positions_path: /pasteur/helix/projects/CSD_hpc/data/lab/spatial/embryo_head_VisiumHD/TenXcountsOutputs/Shah_24_3165p/outs/binned_outputs/square_002um/spatial/tissue_positions.parquet
 segmentation: True
 bin_to_geodataframes: True
 bin_to_cell_assignment: True
 cell_type_annotation: True
 seg_method: stardist
 image_type: he
 nucleus_expansion: True
 expand_by_nbins: 2
 patch_size: 4000
 bin_representation: polygon
 bin_to_cell_method: weighted_by_area
 cell_annotation_method: False
 cell_typist_model: 
 use_hvg: True
 n_hvg: 1000
 destripe_norm: False
 n_clusters: 4
 n_pcs: 250
 chunks_to_run: []
 block_size: 4096
 prob_thresh: 0.005
 overlap_thresh: 0.001
 min_overlap: 28
 context: 128
 n_tiles: (4, 4, 1)
 stardist_modelname: 2D_versatile_he
 channel_to_segment: 2
 cell_markers: {}

2026-01-16 14:24:58,014 - ENACT - INFO - <load_image> Successfully loaded image!
2026-01-16 14:24:58,075 - ENACT - INFO - <normalize_image> Successfully normalized image!
Found model '2D_versatile_he' for 'StarDist2D'.
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.692478, nms_thresh=0.3.
effective: block_size=(4096, 4096, 3), min_overlap=(32, 32, 0), context=(128, 128, 0)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[5], line 12
      1 so_hd = ENACT(
      2     cache_dir="./",
      3     wsi_path="/pasteur/helix/projects/CSD_hpc/data/lab/spatial/embryo_head_VisiumHD/images/A1_highres_RGB.tif",
   (...)
     10     stardist_modelname = '2D_versatile_he'
     11 )
---> 12 so_hd.run_enact()

File ~/venv/enact_venv/lib/python3.10/site-packages/enact/pipeline.py:1350, in ENACT.run_enact(self)
   1345 if not os.path.exists(self.nuclei_df_path):
   1346     # If nuclei_df file does not exist, run Stardist to get cell nuclei
   1347     wsi_norm = self.normalize_image(
   1348         image=wsi, min_percentile=5, max_percentile=95
   1349     )
-> 1350     cell_labels, cell_polys = self.segment_cells(image=wsi_norm)
   1351     # cells_gdf has the nuclei boundaries
   1352     nuclei_gdf = self.convert_stardist_output_to_gdf(cell_polys=cell_polys)

File ~/venv/enact_venv/lib/python3.10/site-packages/enact/pipeline.py:384, in ENACT.segment_cells(self, image)
    382 else:
    383     axes = "YXC"
--> 384 labels, polys = self.stardist_model.predict_instances_big(
    385     image,
    386     axes=axes,
    387     block_size=self.block_size,
    388     prob_thresh=self.prob_thresh,
    389     nms_thresh=self.overlap_thresh,
    390     min_overlap=self.min_overlap,
    391     context=self.context,
    392     n_tiles=n_tiles,
    393     normalizer=None
    394 )
    395 # Store resulting labels as sparse matrix NPZ - super efficient space wise
    396 labels_sparse = sparse.csr_matrix(labels)

File ~/venv/enact_venv/lib/python3.10/site-packages/stardist/models/base.py:930, in StarDistBase.predict_instances_big(self, img, axes, block_size, min_overlap, context, labels_out, labels_out_dtype, show_progress, **kwargs)
    927         print(f"{a}: context of {c} is small, recommended to use at least {o}", flush=True)
    929 # create block cover
--> 930 blocks = BlockND.cover(img.shape, axes, block_size, min_overlap, context, grid)
    932 if np.isscalar(labels_out) and bool(labels_out) is False:
    933     labels_out = None

File ~/venv/enact_venv/lib/python3.10/site-packages/stardist/big.py:448, in BlockND.cover(shape, axes, block_size, min_overlap, context, grid)
    445 assert n == len(block_size) == len(min_overlap) == len(context) == len(grid)
    447 # compute cover for each dimension
--> 448 cover_1d = [Block.cover(*args) for args in zip(shape, block_size, min_overlap, context, grid)]
    449 # return cover as Cartesian product of 1-dimensional blocks
    450 return tuple(BlockND(i,blocks,axes) for i,blocks in enumerate(product(*cover_1d)))

File ~/venv/enact_venv/lib/python3.10/site-packages/stardist/big.py:448, in <listcomp>(.0)
    445 assert n == len(block_size) == len(min_overlap) == len(context) == len(grid)
    447 # compute cover for each dimension
--> 448 cover_1d = [Block.cover(*args) for args in zip(shape, block_size, min_overlap, context, grid)]
    449 # return cover as Cartesian product of 1-dimensional blocks
    450 return tuple(BlockND(i,blocks,axes) for i,blocks in enumerate(product(*cover_1d)))

File ~/venv/enact_venv/lib/python3.10/site-packages/stardist/big.py:186, in Block.cover(size, block_size, min_overlap, context, grid, verbose)
    170 @staticmethod
    171 def cover(size, block_size, min_overlap, context, grid=1, verbose=True):
    172     """Return chain of grid-aligned blocks to cover the interval [0,size].
    173 
    174     Parameters block_size, min_overlap, and context will be used
   (...)
    184 
    185     """
--> 186     assert 0 <= min_overlap+2*context < block_size <= size
    187     assert 0 < grid <= block_size
    188     block_size = _grid_divisible(grid, block_size, name='block_size', verbose=verbose)

AssertionError:
